config/routes.rb
Rails.application.routes.draw do
  root 'blogs#index'
  get 'about' => 'static_page#about'
  devise_for :users
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true

	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs,dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :authenticate_user! ,only:[:new]

  def index
  	@blogs = Blog.all.order(id: "desc")
  end

  def new
  	@blog = Blog.new
  end

  def create
  	@blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
  	if @blog.save
      redirect_to blogs_path
    else
     render 'new'
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.user_id = current_user.id
    if @blog.update(blog_params)
      redirect_to blogs_path
    else
     render 'edit'
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  private
    def blog_params
      params.require(:blog).permit(:title, :category, :body)
    end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/blogs/edit.html.erb
<%= form_for(@blog) do |f|%>
	<%= f.label :title %>
	<%= f.text_field :title %><br>
	<%= f.label :category %>
	<%= f.text_field :category %><br>
	<%= f.label :body %>
	<%= f.text_area :body %><br>
	<%= f.submit "Update Blog"%>
<% end %>

app/views/blogs/index.html.erb
<div id="start-modal" class="start-modal-wrapper">
    <div class="modalbox">
        <h2>Hello,World!</h2>
        <p>"とりあえずやってみる"ときっと成長する</p>
        <br>
        <p>click</p>
        <i class="fas fa-paw close-modal"></i>
    </div>
</div>

	<div class="main-container clearfix">
		<div class="sidebar">
			<% @blogs.each do |blog| %>
				<div class="note-box">
				<div class="note">
				<br>
				<p><strong><%= blog.created_at.to_s(:datetime_jp)%></strong></p>
				<p><strong>Title : </strong><%= blog.title %></p>
				<p><strong>Update : </strong><%= simple_format(blog.body) %></p>
				<div class="block"><p class="tip"><%= link_to 'Edit?',edit_blog_path(blog) ,class: "btn-sticky"%></p></div>
				<div class="block2"><p class="tip"><%=link_to 'Delete?',blog_path(blog),method: :delete ,data: { confirm: 'Are you want to Delete？'},title: 'Excuse me...',class: "btn-sticky2" %></p></div>
				<br>
				</div>
			</div>
			<% end %>
		</div>
		<div class="content">
		</div>
	</div>

app/views/blogs/new.html.erb
<%= form_for(@blog) do |f|%>
	<%= f.label :title %>
	<%= f.text_field :title %><br>
	<%= f.label :category %>
	<%= f.text_field :category %><br>
	<%= f.label :body %>
	<%= f.text_area :body %><br>
	<%= f.submit "Create Blog"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MakiBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="clearfix">
    <div class="top-container">
    <%=image_tag "header.png", class: "header-photo"%>
    </div>
    <div class ="line"></div>
    <div class="menu">
      <nav>
      <ul class="nav-list">
        <% if user_signed_in? %>
        <li class="nav-list-item">
          <%= link_to "Home",root_path%>
        <li class="nav-list-item">
          <%= link_to "About",about_path%>
        </li>
        <li class="nav-list-item">
          <%= link_to "LogOut", destroy_user_session_path, method: :delete %>
        </li>
        <li class="nav-list-item">
          <%= link_to "Entry",new_blog_path%>
        </li>
        <% else %>
        <li class="nav-list-item">
          <%= link_to "Home",root_path%>
        <li class="nav-list-item">
          <%= link_to "About",about_path%>
        <li class="nav-list-item">
          <%= link_to "SignUp", new_user_registration_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "Login", new_user_session_path %>
        </li>
        <% end %>
      </ul>
      </nav>
    </div>
    </div>
  </header>

    <%= yield %>
  </body>
</html>

app/views/static_page/about.html.erb
<div class="container">
	<h1>Hello</h1>
	<p></p>
</div>